version: "3"

services:
  db:
    image: mongo
    volumes:
      - ./datadb:/data/db
    ports:
      - '27017:27017'
  app:
    build: .
    command: npm run server
    volumes:
      - .:/usr/src/app
    ports:
      - '5555:5555'
    depends_on:
      - db
